import type { OsceCaseData } from '../../../shared/ai/schemas';

/* ==========================================================================
   BIBLIOTECA DE ESTAÇÕES (casos curados)
   Mesmo formato do caso gerado pela IA (OsceCase). O roteiro fica oculto
   até o fim da estação. A conversa com o paciente usa a IA (precisa de
   internet); o roteiro em si funciona offline.
   ========================================================================== */

export interface LibraryCase {
  id: string;
  system: string;
  difficulty: 'facil' | 'medio' | 'dificil';
  data: OsceCaseData;
}

export const CASE_LIBRARY: LibraryCase[] = [
  {
    id: 'sca-62m',
    system: 'cardiovascular',
    difficulty: 'medio',
    data: {
      title: 'Homem de 62 anos com dor no peito',
      setting: 'Pronto-socorro',
      patient: {
        initials: 'J.R.',
        age: 62,
        sex: 'M',
        occupation: 'Motorista de ônibus aposentado',
        personality: 'Preocupado, responde de forma direta e simples; no começo minimiza (“deve ser gases”).',
      },
      chiefComplaint: 'Dor no peito',
      openingLine: 'Doutor, tô com uma dor aqui no meio do peito que não passa… deve ser gases, mas minha esposa insistiu pra eu vir.',
      history: {
        hpi: [
          'Começou há cerca de 1 hora e meia, em repouso, assistindo TV.',
          'Dor em aperto/peso no meio do peito (“como um peso em cima”).',
          'Irradia para o braço esquerdo e para a mandíbula.',
          'Intensidade 7/10, contínua desde o início; não muda com a posição nem com a respiração.',
          'Suou frio e teve náusea no início; não vomitou.',
          'Na última semana teve dois episódios curtos (5 a 10 minutos) ao subir a ladeira de casa, que passaram com repouso.',
          'Nunca teve dor assim antes da última semana.',
          'Não tomou nenhum remédio para a dor.',
        ],
        ros: [
          'Leve cansaço; nega falta de ar em repouso, febre ou tosse.',
          'Nega dor nas costas ou dor que “rasga”.',
          'Nega palpitações e desmaio.',
          'Nega dor ou inchaço em uma perna.',
        ],
        pastHistory: ['Hipertensão há 15 anos.', 'Diabetes tipo 2 há 8 anos.', 'Colesterol alto — parou o remédio por conta própria.', 'Sem cirurgias.'],
        medications: ['Losartana 50 mg de 12/12 h', 'Metformina 850 mg de 12/12 h'],
        allergies: ['Nega alergias.'],
        family: ['Pai morreu de infarto aos 58 anos.', 'Mãe com diabetes.'],
        social: ['Fuma 1 maço por dia há 40 anos (40 anos-maço).', 'Cerveja aos fins de semana.', 'Sedentário.', 'Mora com a esposa.'],
      },
      vitals: { pa: '158 x 94 mmHg (semelhante nos dois braços)', fc: '98 bpm', fr: '18 irpm', temp: '36,4 °C', spo2: '96% em ar ambiente' },
      exam: [
        { maneuver: 'Ectoscopia', finding: 'Ansioso, sudoreico, corado, hidratado, acianótico, anictérico.' },
        { maneuver: 'Ausculta cardíaca', finding: 'Ritmo regular em 2 tempos, bulhas normofonéticas, presença de B4, sem sopros.' },
        { maneuver: 'Ausculta pulmonar', finding: 'Murmúrio vesicular presente bilateralmente, sem ruídos adventícios.' },
        { maneuver: 'PA nos dois braços', finding: '158 x 94 mmHg à direita e 154 x 92 mmHg à esquerda (diferença < 20 mmHg).' },
        { maneuver: 'Pulsos periféricos', finding: 'Radiais e femorais simétricos e amplos.' },
        { maneuver: 'Palpação da parede torácica', finding: 'Indolor; não reproduz a dor.' },
        { maneuver: 'Abdome', finding: 'Plano, flácido, indolor.' },
        { maneuver: 'Membros inferiores', finding: 'Sem edema, panturrilhas livres.' },
      ],
      diagnosis: 'Síndrome coronariana aguda — provável infarto sem supradesnível de ST (a confirmar com ECG e troponina), precedido de angina em crescendo.',
      differentials: ['Dissecção aguda de aorta', 'Tromboembolismo pulmonar', 'Pericardite aguda', 'Doença do refluxo / espasmo esofágico'],
      keyQuestions: [
        'Início, duração e se a dor é contínua',
        'Caráter da dor (aperto/peso)',
        'Irradiação (braço, mandíbula, dorso)',
        'Fatores de piora e melhora (esforço, repouso, posição, respiração)',
        'Sintomas associados (sudorese, náusea, dispneia, síncope)',
        'Episódios prévios aos esforços (angina em crescendo)',
        'Fatores de risco cardiovascular (HAS, DM, dislipidemia, tabagismo)',
        'História familiar de doença coronariana precoce',
        'Uso de cocaína e de inibidores de PDE-5 (antes de nitrato)',
      ],
      redFlags: ['Dor em repouso > 20 minutos', 'Sudorese e náusea associadas', 'Dor que rasga irradiando para o dorso (dissecção)', 'Dispneia súbita / fatores de risco para TEP'],
      keyManeuvers: ['Sinais vitais completos', 'PA nos dois braços', 'Ausculta cardíaca e pulmonar', 'Pulsos periféricos', 'Pedir ECG em até 10 minutos'],
    },
  },
  {
    id: 'pac-71f',
    system: 'respiratorio',
    difficulty: 'facil',
    data: {
      title: 'Mulher de 71 anos com febre e tosse',
      setting: 'Pronto-socorro',
      patient: {
        initials: 'M.L.',
        age: 71,
        sex: 'F',
        occupation: 'Costureira aposentada',
        personality: 'Cansada, fala devagar e um pouco ofegante; colaborativa.',
      },
      chiefComplaint: 'Febre e tosse',
      openingLine: 'Ai, doutor(a), tô com essa tosse e uma febre que não me larga desde anteontem…',
      history: {
        hpi: [
          'Há 3 dias começou com febre (até 38,8 °C) e calafrios.',
          'Tosse com catarro amarelo-esverdeado.',
          'Dor do lado direito do peito que piora ao respirar fundo e ao tossir.',
          'Falta de ar ao caminhar dentro de casa desde ontem.',
          'Está comendo pouco e bebendo pouca água.',
          'Tomou dipirona com melhora parcial da febre.',
          'Teve um resfriado na semana anterior.',
        ],
        ros: ['Está orientada; nega confusão.', 'Urinando um pouco menos que o normal.', 'Nega sangue no escarro e dor nas pernas.', 'Nega perda de peso e suor noturno.'],
        pastHistory: ['Hipertensão.', 'Não tem DPOC nem asma.', 'Vacina da gripe em dia; não sabe da pneumocócica.', 'Sem internações recentes; não usou antibiótico nos últimos 3 meses.'],
        medications: ['Hidroclorotiazida 25 mg/dia', 'Anlodipino 5 mg/dia'],
        allergies: ['Teve “manchas vermelhas na pele” com amoxicilina há muitos anos.'],
        family: ['Nada relevante.'],
        social: ['Nunca fumou.', 'Não bebe.', 'Mora com a filha.'],
      },
      vitals: { pa: '128 x 76 mmHg', fc: '104 bpm', fr: '30 irpm', temp: '38,4 °C', spo2: '92% em ar ambiente' },
      exam: [
        { maneuver: 'Ectoscopia', finding: 'Regular estado geral, corada, desidratada 1+/4+, taquipneica, acianótica.' },
        { maneuver: 'Estado mental', finding: 'Lúcida e orientada no tempo e no espaço.' },
        { maneuver: 'Inspeção do tórax', finding: 'Expansibilidade discretamente reduzida à direita.' },
        { maneuver: 'Frêmito toracovocal', finding: 'Aumentado em base direita.' },
        { maneuver: 'Percussão do tórax', finding: 'Macicez em base direita.' },
        { maneuver: 'Ausculta pulmonar', finding: 'Murmúrio vesicular diminuído em base direita, com crepitantes inspiratórios e sopro tubário.' },
        { maneuver: 'Ausculta cardíaca', finding: 'Taquicárdica, ritmo regular, sem sopros.' },
        { maneuver: 'Membros inferiores', finding: 'Sem edema, panturrilhas livres.' },
      ],
      diagnosis: 'Pneumonia adquirida na comunidade em base direita, com CURB-65 = 2 (idade ≥ 65 e FR ≥ 30) — considerar internação; relato de reação cutânea à amoxicilina orienta a escolha do antibiótico.',
      differentials: ['Infecção viral (influenza/COVID-19)', 'Insuficiência cardíaca descompensada', 'Tromboembolismo pulmonar', 'Tuberculose (menos provável pelo tempo de evolução)'],
      keyQuestions: [
        'Duração e evolução da febre e da tosse',
        'Características do escarro',
        'Dor pleurítica',
        'Dispneia e tolerância ao esforço',
        'Confusão mental (CURB-65)',
        'Comorbidades, internação e antibiótico recentes',
        'Alergia a medicamentos (antibióticos)',
        'Vacinação (influenza, pneumococo)',
        'Ingestão hídrica e diurese',
      ],
      redFlags: ['Confusão mental', 'FR ≥ 30 ou SpO₂ < 92%', 'Hipotensão', 'Idade ≥ 65 anos'],
      keyManeuvers: ['Sinais vitais com SpO₂', 'Avaliação do estado mental', 'Frêmito toracovocal', 'Percussão do tórax', 'Ausculta pulmonar'],
    },
  },
  {
    id: 'apendicite-22m',
    system: 'digestorio',
    difficulty: 'facil',
    data: {
      title: 'Homem de 22 anos com dor abdominal',
      setting: 'Pronto-socorro',
      patient: {
        initials: 'P.H.',
        age: 22,
        sex: 'M',
        occupation: 'Estudante universitário',
        personality: 'Inquieto mas evita se mexer; respostas curtas por causa da dor.',
      },
      chiefComplaint: 'Dor na barriga',
      openingLine: 'Tô com uma dor na barriga desde ontem à noite que só piora…',
      history: {
        hpi: [
          'Começou há cerca de 18 horas como dor difusa ao redor do umbigo.',
          'Há umas 8 horas a dor foi para o lado direito, embaixo, e ficou mais forte (8/10).',
          'Piora ao andar, ao tossir e com os solavancos do carro.',
          'Perdeu o apetite desde ontem.',
          'Teve náusea e vomitou uma vez, depois que a dor começou.',
          'Sensação de febre, não mediu.',
          'Evacuou normal ontem; nega diarreia.',
          'Tomou um antiespasmódico, sem melhora.',
        ],
        ros: ['Nega ardência para urinar e sangue na urina.', 'Nega dor nas costas.', 'Nega dor ou inchaço nos testículos.', 'Nega trauma.'],
        pastHistory: ['Sem doenças prévias.', 'Sem cirurgias.'],
        medications: ['Nenhum de uso contínuo.'],
        allergies: ['Nega alergias.'],
        family: ['Nada relevante.'],
        social: ['Não fuma; bebe socialmente.', 'Mora em república.'],
      },
      vitals: { pa: '124 x 78 mmHg', fc: '102 bpm', fr: '18 irpm', temp: '37,9 °C', spo2: '98% em ar ambiente' },
      exam: [
        { maneuver: 'Ectoscopia', finding: 'Desconfortável, prefere ficar imóvel com as pernas fletidas; corado, levemente desidratado.' },
        { maneuver: 'Inspeção abdominal', finding: 'Plano, sem cicatrizes, sem abaulamentos.' },
        { maneuver: 'Ausculta abdominal', finding: 'Ruídos hidroaéreos diminuídos.' },
        { maneuver: 'Palpação abdominal', finding: 'Dor intensa em fossa ilíaca direita, com defesa localizada; restante do abdome flácido.' },
        { maneuver: 'Ponto de McBurney', finding: 'Doloroso.' },
        { maneuver: 'Descompressão brusca (Blumberg)', finding: 'Positiva em fossa ilíaca direita.' },
        { maneuver: 'Sinal de Rovsing', finding: 'Positivo.' },
        { maneuver: 'Sinal do psoas', finding: 'Positivo à direita.' },
        { maneuver: 'Punho-percussão lombar (Giordano)', finding: 'Negativa bilateralmente.' },
        { maneuver: 'Exame testicular', finding: 'Testículos tópicos, indolores, sem aumento de volume.' },
      ],
      diagnosis: 'Apendicite aguda — migração da dor para FID, anorexia, náusea/vômito, dor e descompressão dolorosa em FID e febre (Alvarado ≥ 7 só com os dados clínicos).',
      differentials: ['Linfadenite mesentérica', 'Gastroenterite aguda', 'Ileíte terminal (doença de Crohn)', 'Cólica nefrética à direita', 'Torção testicular'],
      keyQuestions: [
        'Localização inicial e migração da dor',
        'Tempo de evolução',
        'Anorexia',
        'Náusea/vômitos e relação temporal com a dor',
        'Febre',
        'Hábito intestinal (diarreia)',
        'Sintomas urinários',
        'Dor testicular',
        'Fatores de piora (movimento, tosse)',
      ],
      redFlags: ['Dor progressiva com sinais de peritonite', 'Febre alta ou sinais de sepse (perfuração)', 'Dor testicular súbita (torção)'],
      keyManeuvers: ['Palpação abdominal', 'Descompressão brusca (Blumberg)', 'Sinal de Rovsing', 'Sinal do psoas/obturador', 'Giordano', 'Exame testicular'],
    },
  },
  {
    id: 'hsa-45f',
    system: 'neurologico',
    difficulty: 'dificil',
    data: {
      title: 'Mulher de 45 anos com dor de cabeça',
      setting: 'Pronto-socorro',
      patient: {
        initials: 'S.A.',
        age: 45,
        sex: 'F',
        occupation: 'Professora',
        personality: 'Fala baixo, incomodada com a luz; acha que é “mais uma crise de enxaqueca”.',
      },
      chiefComplaint: 'Dor de cabeça forte',
      openingLine: 'É minha enxaqueca de novo, eu acho… mas dessa vez tá muito forte. Dá pra diminuir essa luz?',
      history: {
        hpi: [
          'A dor começou há 5 horas, de repente, na academia, enquanto levantava peso: “como uma pancada na cabeça”.',
          'Chegou ao máximo em menos de 1 minuto — “a pior dor de cabeça da minha vida”.',
          'Dor em toda a cabeça, mais forte na nuca, 10/10, contínua.',
          'Vomitou 3 vezes.',
          'Segundo um colega, “apagou” por alguns segundos logo no início.',
          'As crises de enxaqueca dela são diferentes: começam aos poucos, de um lado, latejantes, com “luzinhas” antes.',
          'Tomou o sumatriptano que usa nas crises, sem melhora.',
        ],
        ros: ['Incomodada com a luz.', 'Nega febre.', 'Nega fraqueza, dormência e alteração da fala.', 'Nega visão dupla.', 'Dor ao mexer o pescoço.'],
        pastHistory: ['Enxaqueca com aura desde a adolescência (2 a 3 crises por mês).', 'Pressão alta “às vezes”, sem tratamento regular.', 'Sem cirurgias.'],
        medications: ['Sumatriptano nas crises', 'Anticoncepcional oral combinado'],
        allergies: ['Nega alergias.'],
        family: ['Mãe teve “aneurisma na cabeça” aos 50 anos.', 'Pai hipertenso.'],
        social: ['Fuma 10 cigarros por dia há 20 anos.', 'Bebe socialmente.', 'Nega drogas.'],
      },
      vitals: { pa: '172 x 98 mmHg', fc: '64 bpm', fr: '16 irpm', temp: '36,8 °C', spo2: '98% em ar ambiente' },
      exam: [
        { maneuver: 'Ectoscopia', finding: 'Desconforto importante, fotofóbica, olhos fechados, corada.' },
        { maneuver: 'Escala de Glasgow', finding: 'Glasgow 15 (O4 V5 M6), discretamente sonolenta.' },
        { maneuver: 'Rigidez de nuca', finding: 'Presente (leve); Brudzinski negativo.' },
        { maneuver: 'Pupilas', finding: 'Isocóricas e fotorreagentes.' },
        { maneuver: 'Pares cranianos', finding: 'Sem alterações; movimentação ocular preservada.' },
        { maneuver: 'Força e sensibilidade', finding: 'Preservadas e simétricas nos quatro membros.' },
        { maneuver: 'Coordenação', finding: 'Sem dismetria.' },
        { maneuver: 'Fundo de olho', finding: 'Sem papiledema.' },
      ],
      diagnosis:
        'Hemorragia subaracnoidea (provável ruptura de aneurisma): cefaleia em trovoada ao esforço, pior da vida, perda transitória de consciência, rigidez de nuca, vômitos e história familiar de aneurisma — regra de Ottawa positiva; TC de crânio imediata.',
      differentials: ['Crise de enxaqueca (diagnóstico de exclusão neste caso)', 'Síndrome de vasoconstrição cerebral reversível', 'Dissecção arterial cervical', 'Meningite', 'Hemorragia intraparenquimatosa'],
      keyQuestions: [
        'Modo de início e tempo até o pico (trovoada)',
        'É a pior dor da vida?',
        'O que fazia quando começou (esforço)',
        'Perda de consciência',
        'Diferença em relação às crises habituais',
        'Vômitos, rigidez de nuca e fotofobia',
        'Déficits neurológicos',
        'Febre',
        'História familiar de aneurisma',
        'Uso de anticoagulantes',
      ],
      redFlags: ['Cefaleia em trovoada', 'Pior cefaleia da vida', 'Perda de consciência', 'Rigidez de nuca', 'Mudança no padrão de uma cefaleia prévia'],
      keyManeuvers: ['Sinais vitais', 'Escala de Glasgow', 'Rigidez de nuca', 'Exame neurológico focal (pupilas, força, pares cranianos)', 'Fundo de olho'],
    },
  },
];
